### ISSUE TITLE
IPFS Project Operations Weekly Sync

### ISSUE THREAD

**Issue by autonome** [ipfs/team-mgmt#1027]
The weekly sync for the [IPFS Project Operations working group](https://github.com/ipfs/team-mgmt/blob/master/TEAMS_ROLES_STRUCTURES.md#project-operations).

* Zoom: https://protocol.zoom.us/j/568955431
* Meeting notes: https://docs.google.com/document/d/1IZ8tyWKnuXKTMbYaZO_8FVUKJ1kxA4imgPaTBhXXbAc/edit#

## About the IPFS Project Operations Weekly Sync

Each week, contributors working on the ongoing operations of the IPFS project meet to track overall progress on quarterly OKRs, high-level status of the core implementations, ongoing collaborations projects, web browser integrations, and the IPFS Desktop, WebUI and Companion projects.

This call grew out of the IPFS Project weekly syncs after the [2019 Q3 reorganization](https://blog.ipfs.io/2019-07-31-operation-task-force/), and now manages several Working Groups that have transitioned to Special Interest Groups (such as In Web Browsers and Desktop & GUI), in addition to project-wide initiatives.

**Who:** Generally full time contributors to the projects listed above, but it's not exclusive, anyone can attend. Be warned, the discussion moves along quickly and is challenging without a lot of context. 

**When:** 30 minutes every Monday at 3:30pm UTC, sometimes cancelled due to holidays. This call can be found in the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Where:** https://protocol.zoom.us/j/568955431

**How:** Prior to the meeting (often just barely) attendees update the week's Google Doc notes, summarizing their progress on key initiatives, and sometimes adding new initiatives that didn't exist in the template. They also add placeholders for announcements, blockers, and general questions that don't fall into a specific initiative. 

During the meeting we work through the notes top to bottom with team members elaborating on their summaries and answering questions from the rest of the team. We take notes as we go so that people who couldn't attend can keep track of progress asynchronously.

**Artifacts:** We take notes of each meeting and post them to [github](https://github.com/ipfs/team-mgmt/tree/master/meeting-notes). We also record each meeting for future reference / async review.

**Comment by andrew** [comment]
@momack2 @autonome should this issue be closed or at least unpinned as it looks like it's not running anymore?

**Comment by momack2** [comment]
Correct - this has been superseded by the ecosystem wg meeting.
