### ISSUE TITLE
📞 Package Managers Weekly Sync

### ISSUE THREAD

**Issue by achingbrain** [ipfs/team-mgmt#1043]
The purpose of this call is to show what we've worked on, to get help with what we're blocked on and to discuss what we're going to work on next.

After the meeting, notes should be added in a PR to [ipfs/team-mgmt](https://github.com/ipfs/team-mgmt) and video uploaded to YouTube.

**Comment by Stebalien** [comment]
# Weekly Sync Oct 1, Tuesday 3:15pm UTC

- 📞 Zoom: https://protocol.zoom.us/j/602589940
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/-Xy8SINyqyaDVudVA0qTaFdC/
- 🎥 Recording:

**Comment by achingbrain** [comment]
# Weekly Sync Oct 15, Tuesday 3:15pm UTC

- 📞 Zoom: https://protocol.zoom.us/j/602589940
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/4crLBnoymlf1wGc8OxFbkqHL/
- 🎥 Recording:

**Comment by Stebalien** [comment]
# Weekly Sync Oct 22, Tuesday 3:15pm UTC

- 📞 Zoom: https://protocol.zoom.us/j/602589940
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/ZTbzy0O0dK2w5V2Olru6MDo2/
- 🎥 Recording:

**Comment by achingbrain** [comment]
# Weekly Sync Nov 5, Tuesday 4:30pm UTC

- 📞 Zoom: https://protocol.zoom.us/j/602589940
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/helRiTw87lY5phjiP24urjVG/
- 🎥 Recording:

**Comment by Stebalien** [comment]
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/MyZFkH-0vkWCdACux5qLTS7m/
- 🎥 Recording:

**Comment by Stebalien** [comment]
# Weekly Sync Dec 03, Tuesday 4:30pm UTC
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/wEgfgoMcYp9KL4LHwdaxtVs3/
- 🎥 Recording:

**Comment by Stebalien** [comment]
# Weekly Sync Dec 12, Tuesday 4:30pm UTC
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/vIzfxtuZpjfAEWAuRataCoNq/
- 🎥 Recording:

**Comment by Stebalien** [comment]
# Weekly Sync Dec 12, Tuesday 4:30pm UTC
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/2dNnbohCTOrSLLByCWFIvGyd/
- 🎥 Recording:
