### ISSUE TITLE
Q4 OKR Scoring ✅

### ISSUE THREAD

**Issue by momack2** [ipfs/team-mgmt#1084]
Hello friends and @ipfs/wg-captains!

The end of the Quarter is coming up and with it, time for us to score Q4 OKRs and reflect on the past quarter! **Please finish grading Q4's OKRs by EOWeek** and do a team retrospective on what is/isn't working by Dec 20 - **team captains are responsible for driving this!** 

To accommodate Q1 planning, we will be doing team OKRs for next quarter in _the beginning of January_ - but please add thoughts and notes to your team retro and ensure that is discoverable in a PR to your OKR md file in this repo (as described below).

The plan is:

<Scoring>

1. Update scores in the [IPFS 2019 Q4 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1685270127) - everyone should fill in the rows that they own
    * `End-Q Actual` - How much progress you made on this KR
    * `Notes on grading` - An update on why you gave it this score (if not obvious)
2. Check the "scoring" box below for your WG
3. Comment on this issue, with a few sentences to recap accomplishments in Q4

<Retro>

4. Create a PR against your group's OKR doc (creating a new doc if needed) -- https://github.com/ipfs/team-mgmt/tree/master/OKR -- to invite team members and the community to **DO A RETROSPECTIVE** on the past quarter and discuss the most important work for the next quarter ([optional template](https://docs.google.com/document/d/1cpMAsP6giMvGR_jaBS4nzdqx2GCOvwOjTbOhLAEPkGI/edit#)).

If you are new to this whole process, check in with your Working Group colleagues and go through the [issue that covers how we did it for 2019 Q1](https://github.com/ipfs/team-mgmt/issues/792) for context. Please post all your remaining questions so that we make sure to get them answered and improve our docs in the process ✨

**End of Q4 OKR Scoring Checklist:**
- [x] [bifrost](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1439867466)
- [x] [testing infra](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=96566767)
- [x] [project operations](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1562851442)
- [x] [package managers](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1685270127)
- [x] [docs](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1841105909)

**Comment by jessicaschilling** [comment]
## DOCUMENTATION & DEVELOPER UX WG

### Summary 
- After a Q3 packed with research, user testing, needs analysis and evaluation, and laying a solid foundation for futureproof work, Q4 saw the docs team acting on these foundational efforts by replacing the outdated, low-functionality, difficult-to use existing docs platform with a revamped, user-friendly successor — set to debut in public beta in the next few weeks — while also undergoing substantial pre-launch user testing and putting into place plans for future improvements to the new docs platform (including a concrete deprecation plan for the legacy site, and user-driven voting for future features!)
- We also paved the way for a content-focused Q1 2020 by onboarding our new technical content strategist, @johnnymatthews, through a focused review of existing materials and roadmapping for determining the content enhancements and user pathways we'll be addressing in Q1 and beyond.
- Additionally, we cleared a substantial amount of "docs debt" (27 issues closed as of last count) discovered either through legacy issue grooming/consolidation or by active feedback via users or site metrics.
- Finally, we introduced a variety of enhancements to ProtoSchool — but I'll leave the explanations of those to @terichadbourne, so as not to take credit for the amazing work done by her and @dominguesgm!

### Useful links
- [Scored Q4 OKRs](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1841105909)
- [Q4 retrospective notes/scratchpad](https://hackmd.io/EaKrgUpWTemmdqTppgN8XQ)
- [Q1 OKR in-progress scratchpad, note VERY WIP](https://hackmd.io/LaQbSAIcSn-wm-jBEDX3FA)
- [PR as required by this process](https://github.com/ipfs/team-mgmt/pull/1085) (though please note that conversation is parimarily being captured in the two scratchpads above)

cc: @terichadbourne @dominguesgm @johnnymatthews @cwaring @ericronne

**Comment by terichadbourne** [comment]
## ProtoSchool 

### Key accomplishments in Q4
- We built a shiny new tutorial on the IPFS Regular Files API. (Kudos to @dominguesgm for producing this great content shortly after onboarding to the team.)
- We reviewed all core and elective course content from IPFS Camp 2019, documenting potential improvements including brand new tutorials, enhancements to existing tutorials, and UX/feature improvements. We've already implemented many of the proposed changes, like incorporating the CID Inspector, and we're excited to build brand new tutorials in 2020 that take advantage of the awesome work the broader IPFS team. 
- To encourage more external contributions, we added new documentation outlining ProtoSchool's capabilities and providing tips for building beginner-friendly content. 
- We tackled under-the-hood issues with error validation and testing to improve the user experience  and completed a review of alternative learning platforms to confirm there wasn't a better solution than our home-grown option. (Thanks to @achingbrain for his error handling contributions!)
- On the community front, we shared a variety of resources with chapter leaders, including ProtoSchool slide deck templates, beginner-friendly IPFS presentations, and the IPFS Camp preso on leading community groups (thanks to @momack2 @akrych @doctorrobinson for their help with these resources). 
- We also launched a local leadership survey for both current chapter leaders and those interested in leading future events, the results of which will guide changes to the local event leadership model in 2020. 

[ProtoSchool Q4 OKRs](https://github.com/ProtoSchool/roadmap/blob/master/okrs/2019-q4.md)

**Comment by autonome** [comment]
##  🎁🎁 Project Operations Q4 Wrap-Up 🎁🎁

Project Operations covers a lot of ground, apologies in advance for length 😅 Results are still coming in, so this is a *DRAFT*.

### IPFS Project prepared for 2020 growth

Our 2020 prep work covered hiring, community, large core implementation endeavors, research and annual project strategy and planning.

* ✅ Hiring: Hiring is multi-quarter work, so some of this was carryover, but by onboarding two Q3 hires and closing two Q4 hires, we hit this goal.
* [TBD - @momack2] 2020 Planning: We've selected a goal for the first half of 2020, but there's still work to be done, such as roadmap updates, team formation and more.
* [0.7] Community: We're prioritizing a community manager hire, so after some research and historical spelunking and talking to various stakeholders we reaffirmed a focus for the role on core contribution, close collaborator contributors, and community channel management. That work got us part of the way to a 2020 community strategy but not all the way. We still need a formalized plan, with feedback and iteration with the team.
* [TBD - @alanshaw] Core Implementations: The big piece of work here is the js-ipfs async/await refactor. This is mostly complete, with patches still landing this week.
* [TBD - @daviddias] Research: The IPFS Research team shares goals with the PL research team, and consisted of publishing five or more Open Problem Statements and three RFPs, and to get publishable versions of papers on our Research (MerkleCRDT, GossipSub, libp2p and new IPFS paper).

### IPFS collaborations supported and broadcast

The collaborations work this quarter was spread across specific collaborations, collab communications, a new grants program and operationalizing the collab pipeline.

* [0.9] Browsers: Brave shipped and announced v1 of IPFS support, and included it in all their launch communication. We received initial builds from Opera and are iterating on changes, helped by a test suite that @lidel created. We planned to ship blog posts about both, but chose to push to Q1 to not compete with the flurry of announcements planned by PL in December. We wanted to get the Brave post written and ready, but didn't get to it before the holidays.
* [TBD - @momack2] Comms: The shared post for p2plab collab and bitswap improvements is TBD.
* [0.9] Grants: @parkan researched, designed and soft-launched the lightweight external IPFS dev grants program at [ipfs/devgrants](https://github.com/ipfs/devgrants) so we can track inbound ideas, “microgrant” opportunities, and to have a place to do grants work in public view.
* [0.9] Collabs Process: We launched the collabs pipeline at the end of Q3, and we spent Q4 using it to evaluate collab opportunities, and to manage ongoing collabs. While a major improvement in systematizing this work, it also made clear that we need yet more changes to make this work highly leveraged, and to build stronger relationships with our close collaborators.

### Level-up day-to-day operations

This objective covers team effectiveness, developer productivity, quality and management of the GUI projects, and our communications infrastructure.

* [0.6] Team effectiveness: The majority of this work was related to leveling-up managers and captains in the form of trainings arranged by @momack2. We didn't get to team-wide trainings this quarter.
* [0.8] Developer Productivity: This was a carry over from Q3 work that @hugomrdias has been pushing on for some time. The major piece was an overhaul of ipfsd-ctl, which is how we set up, coordinate and run tests both manually and from CI. The rewrite means tests are faster and easier to write and change, we have guarantees that the right versions of IPFS are actually being used to run the tests, and also allowed us to massively increase test coverage of js-ipfs when running in the browser, where the majority of tests were previously disabled. There's still work to do updating older tests to the new system, which will carry over into Q1 2020. It's TBD whether the goal of reducing the avg time from js-ipfs PR created to merged by 20% has been hit - really need to measure PR lifetimes over the duration of Q1 to measure this impact.
* [0.8] GUI Maintenance: The primary goal in this area was to create an end-to-end smoketest of webui that can be run in CI by anyone changing that code, by core implementation devs that want to make sure they didn't break webui, and in CI whenever changes happen in any of those projects. @lidel got the infrastructure figured out and then followed with the test automation and test content. It's in reviews now, hoping to land before EOY. However it's not in CI yet, so not quite finished.
* [0.7] Comms: We aimed to complete a communications runbook. @momack2 did a load of work on a [Q4 Comms Plan](https://docs.google.com/document/d/1nk_I9YzZcnkyoK-lVLFZ-m4Qce-_JtOlfDbtGYbfY0k/edit#) with guidance for communicating launches (which we leaned on throughout the quarter), the [Comms Template](https://docs.google.com/document/d/1DVqPK5CXhvfO__mNorZUkkZI1ncUJ3tPp1F-1RZUvyQ/edit#), the [Comms Lessons Learned](https://docs.google.com/document/d/1eg7w_pzBEphNjEapFAYWuyH9siwMQEiuPaKg0vNF_Ho/edit#), and drafted the [Comms Runbook](https://docs.google.com/document/d/1w-mgZ6KHip60NXKYNgPpqXNfG7BioUG-EcEU02I97pE/edit). However, we didn't finish and ship the communication runbook, so there's carry over work for Q1.
