### ISSUE TITLE
🚀 2020 Q1 - OKR Drafting! 🎉

### ISSUE THREAD

**Issue by momack2** [ipfs/team-mgmt#1101]
Hello friends and @ipfs/wg-captains!

Happy New Year!! It's 2020 and therefore time to write down our plans for Q1! Our draft of [top-level project priorities for H1 2020](https://docs.google.com/document/d/15s8lq2iqEsR1_GsKlvXOzWMSJMQ89L7BZ6LA94rzUo4/edit#) (private to wg members for now - but blog post coming soon!) has some early recommendations of what we should take on this quarter and what tasks we should proactively pause ([link](https://docs.google.com/document/d/15s8lq2iqEsR1_GsKlvXOzWMSJMQ89L7BZ6LA94rzUo4/edit#heading=h.1wutbv5l07au
)) - but now we need to convert those into quarterly OKRs by **January 17th**. There may be some shuffles in the works as we solidify on these, but describing the important outcomes we need to shoot for is what helps us orient (and understand better our cross-wg dependencies!)

WG Captains, can each of you please:

1. Create a PR against your group's OKR doc (creating a new doc if needed) -- https://github.com/ipfs/team-mgmt/tree/master/OKR -- to invite team members and the community to discuss the most important work for the coming quarter. See this past example to give you an idea (https://github.com/ipfs/team-mgmt/pull/799)
2. Once the OKRs are ready, push them to the [IPFS 2020 Q1 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=1681757723)
3. Check the [issue for 2019 Q1](https://github.com/ipfs/team-mgmt/issues/792) for context. Please post all your remaining questions so that we make sure to get them answered and improve our docs in the process ✨

**Q1 OKR Drafting Checklist:**
- [x] [Bifrost](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=1439867466)
- [x] [Testground](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=96566767)
- [x] [Ecosystem](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=1562851442)
  - [x] Docs & Developer Experience
  - [x] Collabs & Community
  - [x] Browsers & Connectivity
- [x] [Content Routing](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=1685270127)

**Comment by jessicaschilling** [comment]
Docs is done!

**Comment by momack2** [comment]
While not quite OKRs, the Testground team is tracking progress towards "Milestone 0.1" [in this Zenhub board](https://app.zenhub.com/workspaces/testground-5db6a5bf7ca61c00014e2961/board?milestones=Testground%20v0.1%232020-01-31&repos=197244214)

The content routing group (taking over for core implementations) is scaffolding out the next set of work to strongly improve time to find and start receiving desired content from other nodes [here](https://docs.google.com/document/d/1obd3QHL5QLAUHqi8oxtOl0EYs9bAuPVwz5SWQ53rSvI) and [here](https://docs.google.com/document/d/1obd3QHL5QLAUHqi8oxtOl0EYs9bAuPVwz5SWQ53rSvI/edit?ts=5e26f233#heading=h.2bartnliebsa).
