### ISSUE TITLE
2020 Q2 Planning (and Q1 OKR Scoring) 🎉

### ISSUE THREAD

**Issue by bubbi77** [ipfs/team-mgmt#1126]
Hello friends and @ipfs/wg-captains! @momack2 @autonome @Stebalien @jacobheun @daviddias @raulk @Robmat05 

The end of the Quarter is coming up and with it, time for us to score Q1 OKRs and finalize our plans for Q2! Our aim is to finish grading Q1's OKRs by EOWeek, and then finalize Q2 OKRs by March 27th _(note: the content routing team has a **2 week** extension if needed to focus on 0.5 launch execution)_.

@daviddias has done a great job explaining [how this happens in the past](https://github.com/ipfs/team-mgmt/issues/698) and drafted our [Notes on OKR Planning](https://github.com/ipfs/team-mgmt/blob/master/OKR/README.md#notes-on-okr-planning), which is a great primer on how and why we use OKRs.

The TLDR is:

1. Update scores in the [IPFS Q1 OKRs sheet](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=1681757723) - everyone should fill in the rows that they own!
   - End-Q Actual - How much progress you made on this KR
   - Notes on grading - An update on why you gave it this score (if not obvious)
2. Check the "scoring" box below for your WG
3. Comment on this issue, with a few sentences to recap accomplishments in Q1
4. Create a PR against your group's OKR doc (creating a new doc if needed) -- https://github.com/ipfs/team-mgmt/tree/master/OKR -- to invite team members and the community to discuss the most important work for the coming quarter. See this past example to give you an idea (#799)
5. Once the OKRs are ready, push them to the IPFS 2020 Q2 OKR Spreadsheet (link to follow shortly)
6. Check the "drafting" box below for your WG

If you are new to this whole process, check in with your Working Group colleagues and go through the issue that covers how we did it for 2020 Q1 for context. Please post all your remaining questions so that we make sure to get them answered and improve our docs in the process ✨

End of Q1 Scoring Checklist:

- [x] 🌈[ Bifrost (IPFS Infra)](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=1439867466)
- [x] 🏹[ Testground](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=96566767)
- [x] 🌐[Ecosystem](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=1562851442)
- [x] ⚛️[Content Routing](https://docs.google.com/spreadsheets/d/1vOSCIufWfU2CpG63rOTGVQ6tWNYcbnYvR2k_kN84jQU/edit#gid=1685270127)

Q2 OKR Drafting Checklist (links to follow shortly):

- [x] 🌈[Bifrost (IPFS Infra)](https://docs.google.com/spreadsheets/d/1YTnvQ75v0jCuumOM9CPhx0BZHhJzZGy2u2ydU-rPh2w/edit#gid=0)
- [x] 🏹[Testground](https://docs.google.com/spreadsheets/d/1YTnvQ75v0jCuumOM9CPhx0BZHhJzZGy2u2ydU-rPh2w/edit#gid=2125992746)
- [x] 🌐[Ecosystem](https://docs.google.com/spreadsheets/d/1YTnvQ75v0jCuumOM9CPhx0BZHhJzZGy2u2ydU-rPh2w/edit#gid=2033312819)
- [x] ⚛️[Content Routing](https://docs.google.com/spreadsheets/d/1YTnvQ75v0jCuumOM9CPhx0BZHhJzZGy2u2ydU-rPh2w/edit#gid=238049299)
- [x] 🙌[Project](https://docs.google.com/spreadsheets/d/1YTnvQ75v0jCuumOM9CPhx0BZHhJzZGy2u2ydU-rPh2w/edit?ts=5e83879c#gid=328866436)

If anyone has questions, please post them here :)

**Comment by bubbi77** [comment]
@yunigraham

**Comment by momack2** [comment]
Thanks everyone for getting these landed!

**Looking back at what we achieved towards our H1 focus last quarter:**
1. Build team capacity and velocity ✅
    - New WG structure, impressive trajectory of launches, faster dev cycles with remote colos & testground feedback loop
2. Improve content routing performance ✅
    - Now measuring public DHT content routing metrics!
    - Go-ipfs 0.5.0 currently estimating to be ~7x faster than prod
3. Invest in community enablement ✅
    - Q1 Collabs Interviews delivering useful insights and themes
    - DevGrants completed 4 bounties/devgrants with another  10+ inflight, helping us scale with our community

**Looking into Q2 our core priorities are:**
1. Build Velocity through AUTOMATION 
    - Invest in metrics & automation to ensure we have fast feedback loops and are able to closely monitor progress
    - Ex: Testground 📊 on PRs, nightly canary, stats dashboard
2. <3sec 95% content routing performance
    - Ex: Land 0.5/0.6/0.7, research & build scalable CR solution
3. Smooth & scale collaborator onboarding
    - Execute on collab interview findings to smooth developer onboarding/support & drive IPFS+FIL ecosystem growth
    - Ex: Scale DevGrants, increase collab support tooling, clean up docs/repos, improve dev usage & contribution entry-points

WG OKRs are now in the sheet for reference!
