### ISSUE TITLE
⌚️ DST Switch - next:  2018 Nov 04 (US), Oct 28 (EU)

### ISSUE THREAD

**Issue by lgierth** [ipfs/team-mgmt#433]
Discussion half a year ago: https://github.com/ipfs/pm/issues/231

The conclusion apparantly was to stick with Iceland/Reykjavik time since it doesn't observer DST, but somehow we ended up with 5pm UTC again.

Germany will switch on Sunday 26-Mar.

**Comment by Kubuxu** [comment]
I think we decided that the one hour shift because as everyone's time shifted it worked better for us.

**Comment by diasdavid** [comment]
UTC is the same as Iceland/Reykjavik and same as ZULU, they don't get affected by DST. GMT does, but we don't use GMT anywhere.

See: https://www.worldtimebuddy.com/?pl=1&lid=100,3413829,14&h=3413829

**Comment by lgierth** [comment]
We're switching from 5p UTC to 4p UTC next week. That means sprint calls on 20-Mar will be at 4p UTC.

**Comment by hsanjuan** [comment]
We need to tell the bot that posts the stuff (which is also doing it 5 minutes late). Do we have some machine running this?

**Comment by Kubuxu** [comment]
There is https://github.com/ipfs/infrastructure/tree/master/sprintbot , there is type in server name it is `sprintbot.i.ipfs.io` but my key going through.

**Comment by diasdavid** [comment]
Let's prepare for the next one :) 
![image](https://user-images.githubusercontent.com/1211152/30017321-a7360142-9150-11e7-89f4-7ec762cbfa74.png)

**Comment by diasdavid** [comment]
Can we automate get a notification? @VictorBjelkholm ?

**Comment by vmx** [comment]
Wouldn't it make sense to GMT instead? We use UTC, but shift on daylight savings. That's what GMT is, isn't it?
