### ISSUE TITLE
Reading Material - Project Management

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/team-mgmt#445]
Gathering reference materials for people who want to become better at leading teams and managing projects.

**Comment by diasdavid** [comment]
I do recommend:

![debugging teams](https://images.gr-assets.com/books/1445191687l/26544401.jpg)
![high output management](https://user-images.githubusercontent.com/1211152/29350838-67f8d2ba-8260-11e7-9382-7864920a6657.png)
![peopleware](https://images.gr-assets.com/books/1386925395l/67825.jpg)
![code complete](https://images.gr-assets.com/books/1396837641l/4845.jpg)
![open source software](https://images.gr-assets.com/books/1328834392l/305248.jpg)

#### Not as focused on software teams (or not focused at all) but with super valuable learnings from successful teams and self+team improvement

![](https://images.gr-assets.com/books/1441150227l/6342995.jpg)
![](https://images.gr-assets.com/books/1328747464l/594968.jpg)
![](https://images.gr-assets.com/books/1386607252l/19312976.jpg)

**Comment by Admin-DataRoads** [comment]
[**Drive** by Daniel H. Pink](https://www.goodreads.com/book/show/6452796-drive)
[**Swarmwise** by Rick Falkvinge](https://www.goodreads.com/book/show/18216917-swarmwise)
[**Governing the Commons: The Evolution of Institutions for Collective Action**
by Elinor Ostrom](https://www.goodreads.com/book/show/1048424.Governing_the_Commons)
[**The Utopia of Rules: On Technology, Stupidity, and the Secret Joys of Bureaucracy** by David Graeber](https://www.goodreads.com/book/show/22245334-the-utopia-of-rules)
[**Holacracy: The New Management System for a Rapidly Changing World** by Brian J. Robertson](https://www.goodreads.com/book/show/23526564-holacracy)
[**Sharing Cities: Activating the Urban Commons** by Shareable](https://www.goodreads.com/book/show/37846313-sharing-cities)

**Comment by Admin-DataRoads** [comment]
Some smaller studies, tools, and more recent works supporting the wider ranging list I commented above:
[**Honest Signals: How They Shape Our World** by Alex Pentland](https://www.goodreads.com/book/show/4439706-honest-signals)

[**Evidence for a Collective Intelligence Factor in the Performance of Human Groups** by
Anita Williams Woolley, Christopher F. Chabris, Alex Pentland,  Nada Hashmi, Thomas W. Malone](http://www.chabris.com/Woolley2010a.pdf)

[**That's What She Said: What Men Need to Know (and Women Need to Tell Them) about Working Together** by Joanne Lipman](https://www.goodreads.com/book/show/35181537-that-s-what-she-said)

[**Gender differences and bias in open source: Pull request acceptance of women versus men** by Josh Terrell, Andrew Kofink, Justin Middleton, Clarissa Rainear, Emerson Murphy-Hill​, Chris Parnin, Jon Stallings](https://peerj.com/preprints/1733/)

[**Blind Hiring: A How-To Guide To Reduce Bias & Increase Diversity** by Ji-a Min](https://ideal.com/blind-hiring/)

[**Score Voting** by the Center for Election Science](https://electology.org/score-voting)
