### ISSUE TITLE
Explore possible approaches to Annual Roadmapping

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/team-mgmt#516]
Inspiration: The approach described in the [Rust Lang northstar RFC](https://github.com/rust-lang/rfcs/blob/master/text/1728-north-star.md) and the [2017 Roadmap](https://github.com/rust-lang/rust-roadmap/blob/746a338d7fee9daed8fcb893281aee888908b401/README.md) that they created based on that approach.

It might be the case that this is a good process to adopt _after_ releasing 1.0, but not before.

This approach is compelling in a couple of ways, but we should be careful to consider
- Is it premature for us to plan our roadmap in this way? Setting roadmaps before a 1.0 release has a very different flow than setting roadmaps after 1.0 release.
- It it too process heavy? Will we follow through on applying the process? (example: it looks like Rust have not yet put out a 2017 retrospective, which is a core element of the process described in the RFC.)

Some important observations:
- libp2p and IPFS are quickly evolving towards having separate roadmaps. They already have separate roadmaps for reaching 1.0. Other endeavors (IPLD, multiformats, etc) might evolve to have their own roadmaps too.
- this requires us to get much more explicit about defining working groups, their responsibilities, and their scope

**Comment by daviddias** [comment]
After a much long process of experimentation and collab between all the Working Groups, we know have a Roadmapping process that is set to be updated annually at https://github.com/ipfs/roadmap. Still finishing last details for a proper launch
