### ISSUE TITLE
Upload All Hands recordings to Youtube

### ISSUE THREAD

**Issue by lgierth** [ipfs/team-mgmt#545]
The last upload was on 12-Dec-2017.

Recordings:
- 18-Dec: https://ipfs.io/ipfs/QmNeLBdWJy73sQ3thgpHKapMHoZrVR9MACZU4KA78136yH/zoom_0.mp4
- 8-Jan: https://ipfs.io/ipfs/QmQHYwb9mxFB7URomiHuwqWeSKH258nJCNUmbQMurEV4js/zoom_0.mp4

**Comment by jamiew** [comment]
Calls are all now automatically simulcasted and archived to the "IPFS-dweb" channel on YouTube: https://www.youtube.com/c/IPFS-dweb now

**Comment by diasdavid** [comment]
They still need to get their titles updated so that they can be easy to find later.

**Comment by diasdavid** [comment]
@pkafei can you handle the upload of these?

**Comment by mikeal** [comment]
@diasdavid, @pkafei is out sick right now so she probably won't be able to rely until next week.

**Comment by momack2** [comment]
Closing this out since the meetings and titles are now getting updated.
