### ISSUE TITLE
Reading Material for Working Group Captains and Contributors

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/team-mgmt#550]
As we shift towards planning and executing work as Working Groups, Product Groups, etc, it's important to ensure that everyone has the support and guidance they need in order to contribute to their groups, and potentially to take on leadership responsibilities. One way we can provide support and guidance is to produce a small collection of reference materials, recommended reading and (over time) guides on relevant topics.

To begin with, let's gather reference reading that cover topics like:
- planning a roadmap & estimating time
- writing Product Requirement Documents
- giving feedback 
- encouraging & welcoming contributors 
- dealing with conflict

If you know of good reference materials on these topics, or if you think of a topic that should also be covered, please chime in with a comment on this issue. 

If you're interested in going the extra mile to actually research the topics and assemble a first version of these reference docs, please let me know. Otherwise I will find someone to assemble it.

**Comment by dcwalk** [comment]
If you still need some, my current inspiration!

- [Enspiral on Decision Making](https://medium.com/enspiral-tales/tagged/decision-making)
- [Loomio Cooperative Handbook on Working Together](https://loomio.coop/working_together.html)
- [Mozilla Open Leaders material](https://mozilla.github.io/leadership-training/resources/) (I'm sure you've already seen but I adore 'em so just gonna surface again)
- [Open Decision Framework](https://opensource.com/open-organization/resources/open-decision-framework)
- [Public Lab's Software Outreach](https://publiclab.org/wiki/software-outreach)
- [Fabriders Toolkit](https://www.fabriders.net/category/fabtoolkit/)
- [Aspiration Tech Facilitation Wiki](https://facilitation.aspirationtech.org/index.php?title=Main_Page)

Super interested if you have sources on Mentoring and would be happy to collaborate on a shared braindump resource

**Comment by diasdavid** [comment]
Some of my recommendations https://github.com/ipfs/pm/issues/445#issuecomment-322683890

**Comment by Mr0grog** [comment]
Re: encouraging and welcoming contributors, I recall this episode of The Changelog being a pretty good discussion: [#246: First-time Contributors and Maintainer Balance
with Kent C. Dodds](https://changelog.com/podcast/246)
