### ISSUE TITLE
Proposal: New call for new and open questions or discussion.

### ISSUE THREAD

**Issue by Admin-DataRoads** [ipfs/team-mgmt#573]
Starting with the [IPFS All Hands call 2/12/2018](https://github.com/ipfs/pm/issues/564), we discussed in-call either changing that call or creating something new and more welcoming for diverse newcomers. In response to that call discussion, I made a [quick comment on a prior issue](https://github.com/ipfs/pm/issues/548#issuecomment-365006654), which was about shortening the call to 30 minutes (which seemed at odds with this new proposal, and thus an appropriate place to start proposing a break-off).

Based on that and [All Hands discussion on 2/19/2018](https://github.com/ipfs/pm/issues/572), I am now proposing a new call in lieu of applying any new structure to the existing All Hands Call. @jonnycrunch had the good suggestion to bring new and open https://discuss.ipfs.io questions or discussions into this new call. @Mr0grog questioned whether this might be a good time for a sort of public "office hours" session between newcomers and developers. I think it could also be a good time for new or third-party IPFS API community demonstrations that don't fit into the other public calls.

The Weekly Research call has moved to Wednesdays since we started discussing this, so now I propose making this the main Friday "morning" (16:00 UTC) call. That will give any new questions or discussions time to play out during the week, and a chance to succinctly wrap them up at the end of the week, or at least have them presented in time to make new relevant Agenda items for the next Monday sync up call.

**Comment by djdv** [comment]
Someone had proposed (https://youtu.be/BthIpw5mKTU?t=1339) the idea of also summarizing the answers in text for those that would rather read than attend and/or watch the call.
***

If topics were selected before the call, perhaps something could be written up prior for the textual users and reviewed with additional discussion/details in the call itself. Having prepared sessions may help to control the session lengths and influence topic choice. For instance so that nothing may end up cut short if 2 large topics are selected for 1 call.

**Comment by Admin-DataRoads** [comment]
Based on discussion towards the end of the [All-Hands call 2018/03/19](https://github.com/ipfs/pm/issues/591) there is apparently one point that needs to be clarified here. True and lasting increases to IPFS community diversity is my only motivation for this proposal, and never mere _diversity theater_. This is a similar concept to [Bruce Schneier's coinage _security theater_](https://www.theatlantic.com/national/archive/2014/01/tsa-business-security-theater-not-security/357599/), in that both are for show and do not have any real or lasting effect, or they actually detract from the stated goal by creating showy busywork that takes away from time and resources that could be spent acheiving the real goal. Inviting diverse new faces to an old in-group call that doesn't substantively include them except for inviting some questions in a trailing Q&A, where the claim "there are no bad-looking questions" is obviously false and thus inhibitory to interaction, is just another form of diversity theater. Inviting diverse newcomers to have a venue, a central voice, and the ability to provide some discussion topics and answers of their own is the intended goal here.

**Comment by Mr0grog** [comment]
Would the livestream demo/walkthrough @VictorBjelkholm is suggesting in ipfs/notes#287 be a good first application of this issue?

**Comment by VictorBjelkholm** [comment]
@Mr0grog I think they are different things, but could possibly tie into each other, see https://github.com/ipfs/notes/issues/287#issuecomment-376852813

**Comment by momack2** [comment]
This call actually exists now thanks to the wonderous @olizilla! Join him at 8am PST / 3pm UTC on Mondays (the hour before the IPFS weekly call, in the same zoom room listed in the [IPFS community calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84%40group.calendar.google.com&ctz=Europe%2FLondon)) to discuss any open getting-started issues, be warmly welcomed into the community, help collaboratively answer discourse forum questions, and more!
