### ISSUE TITLE
Working Group Captains Review RFCs 1 & 2 and test the Working Group formation process

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/team-mgmt#629]
I'm asking all of the Working Group captains to 
1. **Review [RFC #1](https://github.com/ipfs/rfcs/pull/1) and [RFC #2](https://github.com/ipfs/rfcs/pull/2).**
2. **Test the Working Group formation process** by formally proposing your current Working Groups and Teams. 

This is not only testing the RFC process, it’s also an opportunity for you all to decide how your Working Groups and Teams should be configured (RFC #2 explains the distinction between working groups and teams). Most of you had WGs handed to you and never had an opportunity to say it should have a different name, or a different description, or a different focus. Now's your chance to propose those changes and discuss them with your collaborators.

**Step 1: Review [RFC #1](https://github.com/ipfs/rfcs/pull/1) and [RFC #2](https://github.com/ipfs/rfcs/pull/2).** Add a +1, -1 (with comments) or abstain with a comment explaining why you’re neither +1 nor -1.  Please do add comments, edits, or suggestions! Don’t be a rubber stamp. Read the RFCs and make them better.

When reading [RFC #2](https://github.com/ipfs/rfcs/pull/2), keep in mind that we will test this process by having your propose your own Working Groups and Teams — so @lidel will propose the Browsers WG and might also propose a separate ipfs-companion Team and someone (@vmx?) will propose a WG for Decentralized Data Structures (choose whatever name you think is right — that’s the point of an RFC), and someone else (@pgte?) should propose a Team for peer-star, peerpad, etc.

**Step 2: Test the Working Group formation process** by proposing your Working Groups and Teams. Use this opportunity to reconfigure your WGs or Teams, to clarify their purpose, etc.

**Comment by lidel** [comment]
+1

@flyingzumwalt are we supposed to wait with **Step 2** until [RFC #2](https://github.com/ipfs/rfcs/pull/2) is merged?
