### ISSUE TITLE
Create a Mailing List for IPFS announcements

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/team-mgmt#634]
Create an ipfs announcements mailing list. Link to the subscription page from ipfs.io website and the README on ipfs/ipfs.

When we create it, 
- [ ] post signup links on ipfs blog
- [ ] post signup links on ipfsbot twitter
- [ ] post signup links on [ipfs-users](https://groups.google.com/forum/#!forum/ipfs-users) mailing list
- [ ] post signup links on an issue on ipfs/ipfs repo (950 followers, 12k "stargazers")

**Comment by Mr0grog** [comment]
We should also add this to the new docs site (either in ipfs/docs#68 or in a new PR if that’s been merged).

**Comment by daviddias** [comment]
@flyingzumwalt should this be something else than the IPFS Newsletter? //cc @mikeal && @renrutnnej

GIven the size of the project nowadays, having a single unified IPFS Newsletter that is well curated does feel like a great current practice.

**Comment by mikeal** [comment]
I'd prefer this just be on the IPFS Newsletter. We could probably create some kind of special section for big "announcements" that is highlights. Thoughts @renrutnnej?

**Comment by daviddias** [comment]
Given lack of activity and the success with the IPFS Newsletter, I'll take that the goal of this proposal has been achieve. Reopen if you feel that is not the case.
