### ISSUE TITLE
⚡️ⒿⓈ Core Dev Team Weekly Sync 🙌🏽 

### ISSUE THREAD

**Issue by daviddias** [ipfs/team-mgmt#650]
> This is a continuation of the thread and process already established at https://github.com/ipfs/js-ipfs/issues/1179

As js-ipfs grows and js-ipld and js-libp2p get their own teams and identity, I decided to properly name this call `⚡️ⒿⓈ Core Dev Team Weekly Sync 🙌🏽 ` vs just _js-ipfs_ as it was before, so that it cleary communicates that it is the weekly sync used by the devs of js-ipfs, js-libp2p and js-ipld to sync up. 

In the future, as teams grow, we might have to separate each team to have each call, but we will let time and need tell us when to do that.

Meanwhile, if you are not familiar with these calls, check the whole thread at https://github.com/ipfs/js-ipfs/issues/1179 and https://github.com/ipfs/js-ipfs/blob/master/MGMT.md.

Also, learn how Work Gets Tracked at https://github.com/ipfs/pm/blob/master/JS_CORE_DEV_MGMT.md

See you all next Monday for the first named ⚡️ⒿⓈ Core Dev Team Weekly Sync 🙌🏽

**Comment by diasdavid** [comment]
# Weekly Sync Up June 25, Monday 5pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://cryptpad.fr/code/#/2/code/edit/lGJ4jNvukmKeVWDbWQiG6q86/

**Recording**: Recording will be uploaded after the call.

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by diasdavid** [comment]
**Update:** With #548, we ca now start the call 30 minutes earlier, that is 4:30pm UTC. I've updated the cal event and the name of the call to the appropriate new name of this call.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1211152/42126155-0cf3c53a-7c7b-11e8-852a-0ce728076af8.png">

# Weekly Sync Up July 02, Monday 4:30pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: 

**Recording**: To be uploaded after the call

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by diasdavid** [comment]
## CANCELED Weekly Sync Up ~~July 09, Monday 4:30pm~~ UTC

There won't be a sync up next week in favor of focusing on the [IPFS Developer Meetings](http://github.com/ipfs/developer-meetings)

**Comment by diasdavid** [comment]
# Weekly Sync Up July 16, Monday 5pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://peerpad.net/#/w/markdown/A7Sj5KpqRmUYx8j4LDdgKs/4XTTMDUzXwpixhvgWTwCt6gtGnSxHkdLPfvodKUpbgxZdujBG/K3TgUxo11YpH2aawzoKh8ovXazdokBwCJU7EMMKDRcrnU28mAzRTAqynCsU79HY99nds7F9MYx7QU9CQvCUdexur1PPdE4jUvChavv62SPQ2tENvbCfmRoiBUec2VAVkW9V8izm8

**Recording**: https://youtu.be/J9QwwVAztpQ

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by diasdavid** [comment]
# Weekly Sync Up July 23, Monday 4:30pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: To be posted Monday morning

**Recording**: To be uploaded Monday after the call

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by diasdavid** [comment]
# Weekly Sync Up August 06, Monday 4:30pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://cryptpad.fr/code/#/2/code/edit/XFVtHCd-0FzXia6wqhn0u0jp/

**Recording**: To be uploaded after the meeting.

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by diasdavid** [comment]
# Weekly Sync Up August 13, Monday 4:30pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://cryptpad.fr/code/#/2/code/edit/8aqx3DbffIh1wrrOnTgC3gxC/

**Recording**: To be uploaded after the call.

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up August 20, Monday 4:30pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://cryptpad.fr/code/#/2/code/edit/2OqeoVCKFIxdMsNCLaaZ2To2/

**Recording**: ADD URL AFTER CALL

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by diasdavid** [comment]
# Weekly Sync Up August 27, Monday 4:30pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://cryptpad.fr/code/#/2/code/edit/6MtuSkKs+NxmYq9uv48GwOje/

**Recording**: Will be uploaded after the recording

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by mgoelzer** [comment]
# Weekly Sync Up September 3, Monday 4:30pm UTC

If you are new to this call and how the JavaScripts projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://cryptpad.fr/code/#/2/code/edit/j+YI0linm3x+qiYhoAFpDK15/

**Recording**: [will post shortly when I know it - of the form https://youtu.be/xxxxxxxxxxxxxxx]

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by diasdavid** [comment]
# Weekly Sync Up September 17, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://cryptpad.fr/code/#/2/code/edit/FvJ-RC-y5HekF1OZP-Ot-k87/

**Recording**: Recording will be uploaded after the call

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by diasdavid** [comment]
# Weekly Sync Up September 24, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/219270872
- Notes: https://cryptpad.fr/code/#/2/code/edit/d-WcQHBRh81qABSmBm+vCS+x/

**Recording**: Recording will be uploaded after the call

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by momack2** [comment]
We are reconfiguring the zoom call setup and that has caused a change in zoom call ID. The **NEW** ID going forward **starting this Monday on Sept 24 is https://protocol.zoom.us/j/443745386**. Please use that link and not the one listed above! I'll also update it in the calendar event going forward.

**Comment by diasdavid** [comment]
# Weekly Sync Up October 01, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/kpeWo0gZXbQ67LRTZsayA0BB/

**Recording**: Recording uploaded after the call

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up October 29, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/-AmIvHIixVr4Tg9+M4S2F2OA/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up November 5, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/qjIC8kDNv86P2hx0l5JLILpD/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up November 12, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/WHhYw94LtAvc2lNfd6GkTejQ/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up November 19, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/NruO92WLT3JueOjk1iV7y-Hc/

**Recording**: TBD

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up November 26, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/OMIbDgMB1hOVU9fyD5eLwmHO/

**Recording**: TBD

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up December 3, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/VhKUsWlBBXH+YyQdydc+V0mC/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up December 10, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/rJSrP7WocY4u8eyCqbsdAIYY/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up December 17, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/sO8VAulwaxLAICZ4Rkd2saFT/

**Recording**: TBD

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up January 07, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/7ZnH-mcheLFoyeNw-CevsOG4/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up January 14, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/7Ivf2HSMFu9zml+uhkvyB62R/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up January 14, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/RsVcG9hy8-7o65Z-TZ39nWP0/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up January 28, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- Zoom: https://protocol.zoom.us/j/443745386
- Notes: https://cryptpad.fr/code/#/2/code/edit/Kcanj9iytttsGXAqqmblMUGH/

**Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up February 04, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/t5BbPbkZHvgFScg0pErvAtDx/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up February 11, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/f7edLo+NvF1bmbi6AJwCsS6T/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up February 18, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/saPbB1MvH8em7+raA5SWQ-Zh/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up February 25, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/nkJ++kBCeEqma0UCCFCraqQh/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up March 04, Monday 5:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/ETA8aq6XIWX-REVhx+rFaWp8/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up March 11, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/mEl9Xt+lfLPF3rIfku9toCg7/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up March 18, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/BDG3k5QxT6FTMzHLKguVgMxn/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up March 25, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/-q-soIAHJYTvScdGBKLoOAd1/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up April 1, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/aST13WT6T7zClAHzBdH8h56z/

🎥 **Recording**: TBC
This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up April 8, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/IBOY2ASt+fgaAdtOtpkN3fyr/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up April 8, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/ZTwB5092xpWtzP0d073qKIxR/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up April 22, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/CMNhdHhAtM+mvP0eeBFWGBjw/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up April 29, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/tGnLlASM5RrL2BIhmw9CLMjt/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by alanshaw** [comment]
# Weekly Sync Up May 13, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/LHlEgWMfeiFSNRFt4+g8oYMC/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up May 20, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/DbFCyuDsw5yOHuF6aNvXkeHk/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by vasco-santos** [comment]
# Weekly Sync Up May 27, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/j-s1SwcljpFmYlRsm7OkzjSv/

🎥 **Recording**: <TO BE ADDED>

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up June 3, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/huge86l9C+tqhmsr+BHLZr4j/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up June 10, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/x2lza-ZQThqPeEweB8uBlux9/

🎥 **Recording**: TBD

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by vasco-santos** [comment]
# Weekly Sync Up May 27, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/kQ63XF1hJGWfwChAdFzpEgRG/

🎥 **Recording**: https://youtu.be/PrScWS9zZJA

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by jacobheun** [comment]
# Weekly Sync Up July 1, Monday 4:30pm UTC

If you are new to this call and how the JavaScript projects are organized, please see the [recording from the first call](https://youtu.be/F0wEg6ZQB34) to learn how we use the waffle board.

- 📞 Zoom: https://protocol.zoom.us/j/443745386
- 📝 Notes: https://cryptpad.fr/code/#/2/code/edit/nZfLOIC9Gh+UXtcvdQBjbdXu/

🎥 **Recording**: TBC

This call is listed on the [IPFS Calendar](https://github.com/ipfs/community#calendar)

**Comment by daviddias** [comment]
### Now there is a join ⚡️ JS & 💫 Go call https://github.com/ipfs/team-mgmt/issues/992
