### ISSUE TITLE
Tracking Impact of All Hands Calls

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/team-mgmt#757]
There were a lot less people on today’s All Hands call than we’ve had in past months. This was probably because of the US holiday, so it might be an anomaly, but it got me thinking about things we should be watching, and things we should make sure to do, as we transition formats.

Three changes that might have affected attendance in today’s call:
- **Veterans Day**: A lot of US participants were probably taking the day off for the national holiday. 
- **Live Stream is now supported**, so people might be watching on there instead of joining the zoom call
- **Format Change**: This switch to emphasize presentations might have removed some incentives for people to join the call, but might create new incentives for participation. Also, the shift to emphasize presentations + announcements might be encouraging people to watch the recording async rather than joining on zoom in real time.

Metrics we should start watching over time, and comparing with prior years:
- **Real-time Participation** via Zoom
- **Viewer counts** on live stream and videos
- **Signups to present** (need to sign post this with a regular announcement at end of calls)
- **Shares and retweets** of info about the calls (if possible)

Other ways to maximize impact of the new format:
- **Promote the recordings after calls**, specifically mentioning the content of the recording. Ie. Tweet a link to today's call announcing that it's a great update by gozala from Mozilla about libdweb
- **Promote presentations in advance** (once the schedule is filled a few weeks out), so people know which talk is coming up and can join if they are especially interested. ie. Tweet saying on next monday's call we'll have a presentation by {{PERSON}} about {{EXCITING_TOPIC}}.

related to PR #739

**Comment by flyingzumwalt** [comment]
cc @terichadbourne @pkafei

**Comment by pkafei** [comment]
Regardless of the reason for the dip, I think it is a good to do some post promotion after the All Hands on Call. Low hanging fruit that comes to mind includes Twitter and posting the video in Discuss.
