### ISSUE TITLE
IPFS All Hands Christmas Eve and New Years Eve

### ISSUE THREAD

**Issue by pkafei** [ipfs/team-mgmt#773]
Should we schedule IPFS All Hands calls for Christmas Eve and New Years Eve?
https://docs.google.com/spreadsheets/d/1XRB2QsPzCPLPOErKvDZfOKK3CMohI9t_QKNdztYMlK0/edit#gid=350755898

Are there any other teams like @ipfs/js-ipfs-io scheduling calls during those days?

**Comment by daviddias** [comment]
Back to the regular schedule :)
