### ISSUE TITLE
IPFS Weekly Call December 3rd, 2018 📞

### ISSUE THREAD

**Issue by pkafei** [ipfs/team-mgmt#782]
# Agenda and Notes

Please add your agenda items before the call.

Endeavour      | Moderator            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | Portia    | $NOTETAKER  | 9:00 **16:00** 18:00  | [agenda and notes](https://docs.google.com/document/d/1WHyIZhBo2eEgYXlZ5HLHg6a6ZWTH3tV848sWkYBJjJA/edit#heading=h.s756z4jd3t6v)

Zoom link for joining the call: https://protocol.zoom.us/j/443621844

**Comment by momack2** [comment]
Hey @pkafei - can we publish the subject of the talk ahead of time in this issue and even more broadly on Twitter/IRC? I think it'd be useful for us all to know the topic of the weekly presentations ahead of time to prep any questions.
