### ISSUE TITLE
 GUI & In Web Browsers Biweekly

### ISSUE THREAD

**Issue by lidel** [ipfs/team-mgmt#790]
> A weekly discussion and show & tell around GUIs and Web Browsers.

- Time: Every other Tuesday @ 4:30 PM UTC, but **check [IPFS Calendar (UTC)](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&ctz=UTC) first**
- Join URL: https://protocol.zoom.us/j/833247793
- **Agenda & Meeting Notes**: https://hackmd.io/QaxiCU8BQqOuK8B8Tdi36g
    - Think if there is something you want to demo. Demos are cool.
    - Feel free to **add your own agenda items** (questions, things to discuss, links others should see)
    - It is encouraged to do so even if you can't attend!
- Past Meetings
  - Recordings: https://www.youtube.com/playlist?list=PLuhRWgmPaHtRIXVTy_ngBwvsXvWw10mR8
  - Notes: [ipfs/team-mgmt/meeting-notes](https://github.com/ipfs/team-mgmt/tree/master/meeting-notes)

**Comment by lidel** [comment]
GUI & In Web Browsers Weekly Sync Notes in December:
- [2018-12-05](https://github.com/fsdiogo/team-mgmt/blob/2dfb93fff622d9d7fc376340cfe7f2b9f381edcd/meeting-notes/2018/2018-12-05--gui-and-in-web-browsers-weekly.md)
- [2018-12-12](https://github.com/ipfs/team-mgmt/blob/197a42719891a5d05bf6cebeabf5f0c2e12604da/meeting-notes/2018/2018-12-12--gui-and-in-web-browsers-weekly.md)
- [2018-12-19](https://github.com/fsdiogo/team-mgmt/blob/a5e92d7ed97b0a57fe6b77c00f4c16247d8d00d0/meeting-notes/2018/Q4/2018-12-19--gui-and-in-web-browsers-weekly.md)

**Comment by hacdias** [comment]
From next week's on, I won't be available at the scheduled hour due to uni classes. I'll be free at the following times (UTC):

- Monday after 6pm
- Tuesday before 12pm, after 6pm
- Wednesday before 11am, after 6pm
- Thursday after 4:30pm
- Friday before 12pm, after 5:30pm

Perhaps we could do a Doodle?

**Comment by lidel** [comment]
I think it makes sense to see if current time slot remains optimal for people interested in GUIs and Web Browsers.

Monday already too busy with various community calls people already attend, so I created Doodle for the rest (time is in UTC): 

- https://doodle.com/poll/y369898g3yh44v8e

@ipfs/wg-gui-team   @hugomrdias  @fsdiogo  @terichadbourne @jimpick @autonome @gozala

**Comment by lidel** [comment]
I think it makes sense to see if current time slot remains optimal for people interested in GUIs and Web Browsers Weekly Sync.

Monday is already too busy with various community calls people already attend, so I created Doodle for the rest of the week + current time (Wen 4pm UTC): 

- https://doodle.com/poll/y369898g3yh44v8e#calendar (you should see your loacal time)

@ipfs/wg-gui-team   @hugomrdias  @fsdiogo  @terichadbourne @jimpick @autonome @gozala

**Comment by olizilla** [comment]
Let's keep this weeks (20th Feb) call at the regular time (4pm UTC), and we can announce any changes that are to happen on the call.

**Comment by olizilla** [comment]
Sorry @hacdias we didn't get around to deciding a new time for the call yet, so next weeks will be at the same time. If we are going to move the call we need to dig around in the doodle poll results, as there doesn't seem to be a clear winner.

**Comment by hacdias** [comment]
@olizilla sure, I'll keep the updates on the doc.

**Comment by lidel** [comment]
There will be GUI & In Web Browsers Weekly call today, as IPFS Q4 All Hands takes place at the time.
See you next week!

**Comment by lidel** [comment]
PSA: we are switching to biweekly: the next call will be on 22nd of April

**Comment by jessicaschilling** [comment]
I'll also put the call details in the readme of https://github.com/ipfs/ipfs-gui when I rework that in the next couple of days 😊

**Comment by lidel** [comment]
PSA: Moved the biweekly call to Tuesday 2:30 PM UTC (from 2020-04-21)

**Comment by lidel** [comment]
We are suspending the call due to reorg. We might come back at some point in the future. :eyes:
