### ISSUE TITLE
It's that time of the Quarter again ✨ - 2019 Q1 Planning 🎉

### ISSUE THREAD

**Issue by daviddias** [ipfs/team-mgmt#792]
Helloo everyone!!!

The end of the Quarter is quickly approaching and with it, it is time for us to do the **OKR Planning Dance for 2019 Q1 🕺🏽💃🏽**!

I've gone in [great length explaining how this happens in the past](https://github.com/ipfs/team-mgmt/issues/698) and I took notes from that thread and incorporated them on our [OKR Notes](https://github.com/ipfs/team-mgmt/blob/master/OKR/README.md#notes-on-okr-planning).

The tl;dr;/TODO list/Summary you have to have in mind is:

- [x] [Score your 2018 Q4 OKRs with End of the Quarter Scores](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=1681757723)
- If you are a Working Group Captain
  - [x] Create a PR against your Working Group doc -- https://github.com/ipfs/team-mgmt/tree/master/OKR -- to get the conversation started. See this past example to give you an idea https://github.com/ipfs/js-ipfs/pull/1566 (note that PR was done on the js-ipfs repo, but since then we moved all the OKR docs to team-mgmt, here https://github.com/ipfs/team-mgmt/tree/master/OKR)
  - [x] Invite the Working Group members and the community to contribute to the discussion.
  - [x] Rely on your fresh minted Working Group Roadmap to seed the conversation https://github.com/ipfs/roadmap/pulls
- [x] Kick off an Async Retrospective for your Working Group following the [Template](https://docs.google.com/document/d/1cpMAsP6giMvGR_jaBS4nzdqx2GCOvwOjTbOhLAEPkGI/edit)
- [x] Once the OKRs are ready, push them to the [IPFS 2019 Q1 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=1681757723)

If you are new to this whole process, check in with your Working Group colleagues and go through the [issue that covers how we did it for 2018 Q4](https://github.com/ipfs/team-mgmt/issues/698), it will provide you a great deal of context. Nevertheless, post all your questions so that we make sure to get them answered and improve our docs in the process ✨

**Comment by daviddias** [comment]
[PR for Project WG Open OKR Planning](https://github.com/ipfs/team-mgmt/pull/793)

**Comment by daviddias** [comment]
Also, has it is now traditional, there will be an Open Call to introduce OKRs to everyone led by @steverichmond on Dec 19th.

The agenda looks like this: 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/1211152/49699447-987f0d00-fbd1-11e8-9872-36ac46495416.png">

**Comment by daviddias** [comment]
@ipfs/working-group-captains

**Comment by momack2** [comment]
We have one for Local Offline Collab here: https://github.com/ipfs/local-offline-collab/issues/5

**Comment by daviddias** [comment]
Hi everyone again! 

Today I've a "protip" to share with you all. To avoid the trap of overloading your OKRs spreadsheets, consider checking in on how much time you have actually available during the quarter an plan for 60% of that only.

Q1 roughly looks like this
<img width="701" alt="image" src="https://user-images.githubusercontent.com/1211152/50134450-ee198080-0287-11e9-8adc-651a56603daf.png">

Nevertheless, that is the maximum available. You should take out the days you are going to spend at conferences, hack weeks, research retreats, etc and only then calculate your 60%. Here is an example:

- 13 weeks in the quarter - 65 days (assuming 5 day work week)
- Take out the first 2 days (NYE and Jan 1) - 63
- Now if you happen to have planned 15 days of Vacation + Hack Weeks + conferencing, etc. Then you have left 48 days.
- 48 days in a 8 hour work day is 384 hours
- 60% of that is 230.4 hours

In this example, the OKRs should only contemplate work you could do in **230.4**. And yes, it is incredibly hard to estimate how much time a task does, but we often fall into the trap of planning 3x to 5x the work we could possibly do in the time we have available, so this exercise is a good tool to help us prioritize and drop stuff right before the Quarter starts.

See my calculation here -- https://github.com/ipfs/team-mgmt/pull/793#issuecomment-448093921
