### ISSUE TITLE
clinicjs introduction - Benchmarking IPFS - Dec 11, 2:30pm UTC

### ISSUE THREAD

**Issue by mcollina** [ipfs/team-mgmt#796]
Hi Folks,

In this session we will present https://clinicjs.org/, our suite of tool for finding bottleneck in Node.js code. We will also walk you through running clinic locally with the benchmarks we have developed at https://github.com/ipfs/benchmarks.

The session will be on at 2:30pm UTC.

Zoom: https://nearform.zoom.us/j/115579475.

The session will be recorded.

**Comment by daviddias** [comment]
Ah, it's today? Nice! Glad I asked to open the issue as I totally thought it would be wednesday

**Comment by mcollina** [comment]
Here are the recordings: https://nearform.zoom.us/recording/play/A-4Vn3jA5aeK9BCPwKCA44IfwpLZePIBlzvD1bUYF7JqTXnG2JptVaLEVcRUmQ1i?continueMode=true
