### ISSUE TITLE
Idea: Using ZeroMQ's C4 as a template for code and community management

### ISSUE THREAD

**Issue by DonaldTsang** [ipfs/team-mgmt#834]
Abstract:
Please read the markdown document [here](https://github.com/zeromq/rfc/blob/master/44/README.md) for more information in regards to implementing code management.
Reasoning:
As a user of IPFS I am very concerned that fatal bugs like https://github.com/ipfs/go-ipfs/issues/4558 are causing issues for people who uses the library
(The application I use using IPFS are Siderus Orion and Hydrus, which both has issues in regards to the bug referenced above)

**Comment by momack2** [comment]
Thanks for the note @DonaldTsang - I took a pass through ZeroMQ and was wondering if you could explain the pieces of that model that you think would be particularly valuable/new for the IPFS project? I don't understand from the referenced bug what process components might have prevented it.

**Comment by DonaldTsang** [comment]
@momack2 I was concerned that the bug (as an example, among other critical bugs) has not been patched for a whole year unnoticed, and since I have gone to multiple coding conferences with people recommending ZeroMQ's C4 model. I think it is a good idea to ask if that could be useful for IPFS or not.

**Comment by momack2** [comment]
@DonaldTsang - you may appreciate the improved release process and rigor about minor and patch releases we're introducing to go-ipfs: https://github.com/ipfs/go-ipfs/blob/master/docs/releases.md. While not exactly the ZeroMQ process, we did learn from the guidelines there so thank you for suggesting it!

**Comment by DonaldTsang** [comment]
@momack2 finally something wholesome! this is what will make IPFS good to manage
