### ISSUE TITLE
Pull in the Four Latest IPFS Weekly Videos

### ISSUE THREAD

**Issue by pkafei** [ipfs/team-mgmt#851]
We want the[ Looking for Inspiration](https://github.com/ipfs/team-mgmt/blob/master/IPFS_WEEKLY_CALL.md#if-youre-looking-for-more-inspiration-check-out-some-of-our-past-talks) section of [IPFS Weekly Call](https://github.com/ipfs/team-mgmt/blob/master/IPFS_WEEKLY_CALL.md) to always include the latest IPFS Weekly Call recordings. 

Instead of manually updating this section, we should have a script that automatically populates the _Looking for Inspiration_ section with the most recent recordings.

**Comment by momack2** [comment]
I did this and also revamped the structure of our youtube channel to better highlight our new content, weekly presentations, and working group sync ups.
