### ISSUE TITLE
Circle CI v2.0 migration

### ISSUE THREAD

**Issue by mburns** [ipfs/team-mgmt#879]
A couple dozen IPFS repos have a legacy Circle CI config that needs to be remove/upgraded.

There is a hard deadline of [March 15, 2019](https://circleci.com/sunset1-0/) to migrate.

IPFS:
- [x] https://github.com/ipfs/interface-datastore/blob/master/circle.yml
- [ ] https://github.com/ipfs/ipfs-geoip/blob/master/circle.yml
- [x] https://github.com/ipfs/distributions/blob/master/circle.yml
- [ ] https://github.com/ipfs/project-repos/blob/master/circle.yml
- [ ] https://github.com/ipfs/js-ipfs-merkle-dag/blob/master/circle.yml
- [x] https://github.com/ipfs/js-ipfs-block-service/blob/master/circle.yml
- [x] https://github.com/ipfs/js-libp2p-ipfs-nodejs/blob/master/circle.yml
- [x] https://github.com/ipfs/js-libp2p-ipfs-browser/blob/master/circle.yml
- [x] https://github.com/ipfs/js-ipfs-block/blob/master/circle.yml
- [ ] https://github.com/ipfs/paperhub/blob/master/circle.yml
- [ ] https://github.com/ipfs/protons/blob/master/circle.yml
- [ ] https://github.com/ipfs/interface-pull-blob-store/blob/master/circle.yml
- [ ] https://github.com/ipfs/js-fs-pull-blob-store/blob/master/circle.yml
- [x] https://github.com/ipfs/js-idb-pull-blob-store/blob/master/circle.yml
- [ ] https://github.com/ipfs/js-level-pull-blob-store/blob/master/circle.yml
- [x] https://github.com/ipfs/go-ipfs-cmds/blob/master/circle.yml
- [x] https://github.com/ipfs/js-datastore-core/blob/master/circle.yml
- [ ] https://github.com/ipfs/ipfs-ds-convert/blob/master/circle.yml

IPFS-Shipyard:
- [ ] https://github.com/ipfs-shipyard/ipscend/blob/master/circle.yml
- [ ] https://github.com/ipfs-shipyard/y-ipfs-connector/blob/master/circle.yml
- [ ] https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/master/circle.yml
- [ ] https://github.com/ipfs-shipyard/shared-editing-demo/blob/master/circle.yml
- [ ] https://github.com/ipfs-shipyard/ipfs-pubsub-1on1/blob/master/circle.yml

To remove, delete the `.circle.yml` or `.circleci/config.yml` file and then click `unfollow project` in the Circle CI website.

**Comment by daviddias** [comment]
Is this still a thing?

**Comment by mburns** [comment]
I've updated the checklist to reflect reality. All the repos we maintain were updated.
