### ISSUE TITLE
Waffle is closing in May 2019. Discussing alternatives.

### ISSUE THREAD

**Issue by 0zAND1z** [ipfs/team-mgmt#930]
Hi all,

As you may have observed by now, waffle is closing waffle.io on 16th of May 2019.

Does IPFS has a transition plan in place to a new PM tool?

Can we invite the developer community to suggest a few options here?

Looking for a productive dialogue & outcome. 

Thanks.

**Comment by 0zAND1z** [comment]
ZenHub seems to be a nice PM tool. I have been using it for a while now & also has really productive browser extensions to manage the work items within GitHub.

Take a look at it here: https://www.zenhub.com/
Browser Extensions: https://www.zenhub.com/extension

**Comment by momack2** [comment]
As @ericronne correctly notes, Github Project Boards are becoming more popular/capable for this sort of need. There are even some external tools that empower automating some of the gaps: https://medium.com/the-andela-way/how-to-build-a-power-up-for-your-github-project-board-for-project-management-344d5b380a68

**Comment by ericronne** [comment]
Zenhub is great, and a potential fallback. Projects isn't quite as full-featured at this point, but it's native, and proven useful in the past, so … 🤞

I plan to have the board set up this week, stay tuned!

**Comment by ericronne** [comment]
Good news: board access for the Protocol org has now been unlocked, thanks to @jesseclay!
Less-good news: project boards can only be linked to repos within a **single organization**. Consequently we wouldn't be able to track PL, Filecoin, and IPFS design issues together on a single board. We could create one project per org, but that doesn't satisfy the brief: One Board to Track Them All.

Zenhub *does* allow cross-org linking, but a max of only five repos can be connected to a board (*plus* a repo can only be linked to one zenhub board, so we would potentially lock others out of zenhub access for their repos — or vice versa).

So unless @olizilla is able to devise a clever workaround (🙏), the current best option may be to simply wire up the Design Shop repo ([like so?](https://medium.com/the-andela-way/how-to-build-a-power-up-for-your-github-project-board-for-project-management-344d5b380a68)) to the newly created Protocol org [project board](https://github.com/orgs/protocol/projects/3), and use that to prioritize and track that repo's issues. This will allow box 2 of [this issue](https://github.com/protocol/LabOS/issues/104#issuecomment-479673726) to be checked.

This basically replicates the current waffle board functionality.

**Comment by daviddias** [comment]
> Zenhub does allow cross-org linking, but a max of only five repos can be connected to a board. 

It only lets you link five repos in the first round. Once the Workspace (what they call aboard) is created, you can link more.

> so we would potentially lock others out of zenhub access for their repos

I believe this can be a nice way to enforce "a repo is own by a single WG/Team" and in turn, instead of having multiple Working Groups trying to manage the same issues and create the labels explosition, something that @meiqimichelle encountered multiple times in the past (and so did I), it would encourage everyone to create a new issue that links to the other issues on the other Working Group turf.

I gave Zenhub a try today and I was very happy to see that they now have a standalone app and everything :) https://app.zenhub.com/

**Comment by 0zAND1z** [comment]
@daviddias , true dat. Drastic new changes have happened to ZenHub & the very reason why I suggested.

I believe the developers & the community can achieve a lot more comprehensive clarity if we consider ZenHub. Looking forward to thoughts from other contributors as well..

**Comment by ericronne** [comment]
Yes, zenhub [workspaces](https://help.zenhub.com/support/solutions/articles/43000504792-workspaces-what-s-new-) may have arrived just in time to save the day.

```With Workspaces we have removed the 1-1 mapping of Board-to-Repo, allowing a repository to be added to multiple Boards. In other words, Issues and Epics can be added and updated in different Workspaces at the same time yet have an independent pipeline allocation for each Workspace.```

**Comment by ericronne** [comment]
[Looking promising](https://app.zenhub.com/workspaces/pl-design-5bede55c4b5806bc2bf518e1/board?repos=83828178,106405473,90972988,114143402,111841602,20755034,170111302,126995088)

[note re plan](https://github.com/protocol/LabOS/issues/104#issuecomment-494980749)

**Comment by 0zAND1z** [comment]
> [Looking promising](https://app.zenhub.com/workspaces/pl-design-5bede55c4b5806bc2bf518e1/board?repos=83828178,106405473,90972988,114143402,111841602,20755034,170111302,126995088)

Awesome! Let me know if you need any help. 

If it helps, here's a [sample epic ](https://app.zenhub.com/workspaces/tara-dev-5c3e1c26ca7fa74504b9153c/issues/taraframework/go-tara/30) on the [ZenHub board](https://app.zenhub.com/workspaces/tara-dev-5c3e1c26ca7fa74504b9153c/board?repos=121188920) linked to a milestone, and fully fledged with dependent/blocking tasks from one of my garage project.

> [note re plan](https://github.com/protocol/LabOS/issues/104#issuecomment-494980749)

Well, I could not access this. Seems to be a private repo I don't have access to.

**Comment by ericronne** [comment]
> Well, I could not access this. Seems to be a private repo I don't have access to.

Yep. I was thanking you in a related internal conversation :)
```Shout out to @daviddias, @0zAND1z, and @mishmosh for making us aware of this new feature 🙌```
Thanks again!

**Comment by momack2** [comment]
Teams doing kan-ban-ing are now using ZenHub and while it is a little less accessible than waffle was (have to sign in with your github acct and give zenhub access to any private repos) it's working relatively well for us. Closing this out given we found a good alternative.
