### ISSUE TITLE
New Contributor - Localisation

### ISSUE THREAD

**Issue by djdakta** [ipfs/team-mgmt#932]
Hi,

My name is Dakta and I'm new to IPFS.
I would like to contribute on translating IPFS from English to French.
I'm a Freelance translator for different projects: Microsoft MakeCode, Grav Admin & Grav Core, Thunderbird Mail client, ...

**Comment by momack2** [comment]
Hi Dakta, check out the ipfs translation project
(https://github.com/ipfs/i18n) for instructions and how-to guide to
contribute your translations. Welcome to the project!
