### ISSUE TITLE
Deleting some repos in the "ipfs" org

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/team-mgmt#970]
This is a list of repos that I think can be safely thrown away:

* https://github.com/ipfs/astralboot (fork with no differences from source)
* https://github.com/ipfs/golang-build (fork never worked on) 
* https://github.com/ipfs/opentracing-go fork for supporting go modules and Gx but `opentracing-go` is used as `opentracing/opentracing-go` everywhere that I can find.

**Comment by mburns** [comment]
in a similar vein (tracked in https://github.com/protocol/infra/issues/470) the following repos can be **archived**:

* https://github.com/ipfs/jenkins
* https://github.com/ipfs/jenkins-libs

**Comment by Stebalien** [comment]
> https://github.com/ipfs/astralboot (fork with no differences from source)

This may have been an attempt to backup/promote this project. I'm guessing @jbenet will want to keep it.

> https://github.com/ipfs/golang-build, https://github.com/ipfs/opentracing-go

:+1: These look like they've never really been used.

**Comment by Mr0grog** [comment]
FYI, there is a longer version of this in checklist form here: https://github.com/ipfs/docs/issues/54

**Comment by hsanjuan** [comment]
Thanks. Action has been taken on the repos mentioned here (we leave astralboot for the moment). Closing this issue and deferring to https://github.com/ipfs/docs/issues/54
