### ISSUE TITLE
2019 Q2  - Midpoint OKR Scoring

### ISSUE THREAD

**Issue by momack2** [ipfs/team-mgmt#979]
It is the time of the quarter ⏱ where we check in on progress and chart our trajectory for the rest of the quarter (i.e. course correct to get back on track or intentionally drop KRs to focus remaining efforts).

@ipfs/wg-captains - y'all have done this before, nevertheless here's the ask for each WG:

1. Update scores in the [IPFS Q2 OKRs sheet](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1681757723) - everyone should fill in the rows that they own
    * `Mid-Q Actual` - How much progress you have made on this KR
    * `Mid-Q Projection` - How much progress you believe you will have made by the end of the quarter
    * `Notes on grading` - An update on why you gave it this score (if not obvious)
2. Check the box below for your WG
3. Comment on this issue, with a few sentences to recap
4. Review progress and help individual contributors reallocate energy to the highest priority, highest impact KRs
5. Check in on the results during your next WG Weekly Sync and carry on for the rest of the quarter 🚀

**Checklist:**
(despite our reshuffle into fewer core WGs, we are still finishing out the quarter with _our current OKR sheets_, so this list is larger than it will be next quarter. If I've missed any, please chime in to correct!)
- [x] [project](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1562851442)
- [ ] [go-ipfs](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1720716278)
- [x] [js-ipfs](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=274358435)
- [x] [ipfs-cluster](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=2055463539)
- [ ] [ipfs-gui](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1841105909)
- [ ] [ipfs-wb](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=755202447)
- [ ] [ipfs-pm](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1685270127)
- [x] [ipfs-ddc](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=27675624)

If anyone has questions, please post them here :) Happy mid quarter scoring!

**Comment by momack2** [comment]
[**ipfs-project WG**](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1562851442) is scoring **0.2** at mid-quarter, and on track to hit ~**0.7** by end of quarter. Many of our goals this quarter are about events landing at the end of Q2 - so  "Mid-Q Actuals" aren't reflective of the significant effort put into these KRs that won't be measured until EOQ.

Going well:
- Package manager demos, documentation, and research is proceeding well and providing good insight into how we can make IPFS more usable, performant, and capable
- IPFS Camp preparation is on track to expectations, and we anticipate high a event satisfaction ratings due to our amazing attendee list, content prep, and event coordination
- Cultural values have a pretty high fidelity draft and have spurred great conversation with the team

Going well needs a nudge:
- IPFS Team Week Agenda and facilitation has come together - but we still have a lot of content to prepare across the team! Project leads will be focusing main attention to getting this content prepped (or formats solidified) the next few weeks
- Community / Comms / Docs is still an area of weakness - we need to spec out the P0 tasks we'd like someone to pick up and the qualities we're looking for in a great owner for this work stream
- Security audit sounds like it may be slipping into next quarter based on the Libp2p phase 1 & 2 timing - other than staying on people's radar, we can investigate internal pre-audits to identify potential issues internally first to help move this along
- Still need to transform package manager research and findings into a prioritized and scaffolded roadmap of work through the end of the year

Intentionally de-prioritized:
- Collab threads and coordination are making good progress, but we have delayed pipeline systemization / regular updates to next quarter so we can focus on IPFS Camp prep

**Comment by momack2** [comment]
Ping! Please aim to complete this by EOWeek @alanshaw @Stebalien @hsanjuan @olizilla @lidel (and also @achingbrain and @jimpick / @aschmahmann)

**Comment by terichadbourne** [comment]
[Q2 mid-quarter and projected scores for ProtoSchool](https://github.com/ProtoSchool/roadmap/blob/master/okrs/2019-q2.md) are now available. ProtoSchool is being fostered by the GUI team for the time being and the additional support from @fsdiogo and @olizilla has allowed us to make some huge leaps forward in UX, as well as prepare the MFS tutorial which will be released between now and IPFS Camp. UX improvements for chapter leadership have taken a backseat as we've intentionally focused on content creation to make the chapter model more sustainable.

**Comment by aschmahmann** [comment]
IPNS Update:
- Improved Go-IPNS performance is well underway (there are branches of go-ipfs available with this working).
- A multiwriter IPNS over PubSub is working and passing tests at https://github.com/aschmahmann/ipshare (still needs work/thoughts on how to layer on ACL/permissioned behavior)
- Rendezvous and PubSub changes need work/time before changes get accepted into master
- Need more consolidated IPNS documentation

**Comment by autonome** [comment]
In Web Browsers...

* The work on IPFS Camp courses continues apace. The Core Course C team demo'd the material for  in the GUI & WB meeting this week, and the Turning Browsers into True User Agents elective course is midway from outline to content. The 🚂 is on the tracks.

* @hugomrdias' work on hyperspeed IPNS resolve times, in support of camp and package manager efforts, is projected to arrive at the station on schedule.

* The surprise of web developers will be much reduced, seeing as @hugomrdias already got Vue-CLI and web file APIs working, and @lidel projects that CIDv1 Base32 for subdomains with mutable content is going to be ready as well.

* Browser integration está moviendo rápido! @lidel has a tight feedback loop with Brave and is working with them to get Companion integration working smoothly in time for showing off at Camp. A plan for supporting Opera's work will be ready by end of quarter.

There are a few other bits and bobs that may or may not make it, as we turn our attention fully to being ready for IPFS Camp 🏕 But our P0 projections from Lisbon at end of March are looking bang on for the most part.

**Comment by hsanjuan** [comment]
Cluster:

* We merged CRDT-based consensus layer and all the things we needed around it
* On track to have a nice pinning service in IPFS Camp, also on track with courses and workshops
* On track with documentation revamp efforts

Current avg projection is: 0.6 (but we have some items that are very low prio). P0s however are in very good state and already killed some of them.

**Comment by daviddias** [comment]
Q2 done?

**Comment by momack2** [comment]
Thanks for the great updates folks! Very useful for indexing in on progress. Now on to end of quarter grading! =]
