### ISSUE TITLE
Publish/Livestream go-ipfs videos to IPFS YouTube Account

### ISSUE THREAD

**Issue by momack2** [ipfs/team-mgmt#984]
In order to make it easier to index on what the go-ipfs team is working on (and folks who were out to catch back up quickly), I think it'd be great if we quickly published go-ipfs weekly meetings to YouTube like the other IPFS Working Groups. Folks on the call noted that this would be most useful if we linked in the week's notes so folks have something to read through while listening to dense updates. 

I imagine the person PRing the notes to the team-mgmt issue would also ensure the recording was uploaded or livestream was flipped to "public". @ipfs/wg-go-core - would love any thoughts? @djdv tentatively offered to do the first few since he has experience doing this in the past.

**Comment by daviddias** [comment]
Now with #992, this is not a question anymore right?

**Comment by momack2** [comment]
correct
