### ISSUE TITLE
2019 Q3 Planning (and Q2 OKR Scoring)

### ISSUE THREAD

**Issue by momack2** [ipfs/team-mgmt#995]
Hello friends and @ipfs/wg-captains!

The end of the Quarter is past and with it, time for us to score Q2 OKRs and finalize our plans for Q3! Our draft of [top-level project priorities for Q3](https://docs.google.com/document/d/11w8hP9OFbMYebuhCDFF63r3zjvur0dslgQnAhqtBgpo/edit#) has already driven the team to restructure into problem-oriented task forces to organize our work for Q3. Now for writing it down!

@daviddias has done a great job [explaining how this happens in the past](https://github.com/ipfs/team-mgmt/issues/698) and drafted our [Notes on OKR Planning](https://github.com/ipfs/team-mgmt/blob/master/OKR/README.md#notes-on-okr-planning), which is a great primer on how and why we use OKRs.

The TLDR is:

1. Update scores in the [IPFS Q2 OKRs sheet](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1681757723) - everyone should fill in the rows that they own
    * `End-Q Actual` - How much progress you made on this KR
    * `Notes on grading` - An update on why you gave it this score (if not obvious)
2. Create a PR against your group's OKR doc (creating a new doc if needed) -- https://github.com/ipfs/team-mgmt/tree/master/OKR -- to invite team members and the community to discuss the most important work for the coming quarter. See this past example to give you an idea (https://github.com/ipfs/team-mgmt/pull/799)
3. Once the OKRs are ready, push them to the [IPFS 2019 Q3 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1681757723)

If you are new to this whole process, check in with your Working Group colleagues and go through the [issue that covers how we did it for 2019 Q1](https://github.com/ipfs/team-mgmt/issues/792) for context. Please post all your remaining questions so that we make sure to get them answered and improve our docs in the process ✨

**End of Q2 Scoring Checklist:**
(despite our reshuffle into fewer core WGs, we are still finishing out the quarter with _our current OKR sheets_, so this list is larger than it will be next quarter. If I've missed any, please chime in to correct!)
- [x] [project](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1562851442) - 0.7
- [x] [go-ipfs](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1720716278) - 0.4
- [x] [js-ipfs](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=274358435) - 0.5
- [x] [ipfs-cluster](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=2055463539) - 0.3
- [x] [ipfs-gui](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1841105909) - 0.5
- [x] [ipfs-wb](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=755202447) - 0.7
- [x] [ipfs-pm](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1685270127) - 0.5
- [x] [ipfs-ddc](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=27675624) - 0.2

**Q3 OKR Drafting Checklist:**
- [x] [ipfs as a service](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1439867466)
- [x] [testing infra](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=96566767)
- [x] [project operations](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1562851442)
- [x] [package managers](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1685270127)
- [x] [docs](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1841105909)

If anyone has questions, please post them here :)

**Comment by autonome** [comment]
DDC Q2 OKRs all appear to have scores now ✅
